version: 2.1
 
orbs:
  cicd: sedstart/cicd@1.0.1
jobs:
  run-sedstart-local-linux:
    docker:
      - image: cimg/node:25.2.1
    steps:
      - cicd/runcloud:    
          api_key: SEDSTART_API_KEY     
          project_id: 1296
          suite_id: 1085
          profile_id: 2307
          browser: chrome
          headless: true
workflows:
  test-workflow:
    jobs:
      - run-sedstart-local-linux
